package com.gestion_de_pqrs.gestion_pqrs;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class DATOS_PQRS implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("CLIENTE")
	private java.lang.String cliente;

	@org.kie.api.definition.type.Label("TIPO DE NOVEDAD")
	private java.lang.String tipo_novedad;

	@org.kie.api.definition.type.Label("DESCRIPCION DE LA NOVEDAD")
	private java.lang.String descripcion_novedad;

	@org.kie.api.definition.type.Label(value = "OTRA SOLICITUD")
	private java.lang.String otra_solicitud;

	@org.kie.api.definition.type.Label(value = "AREA RESPONSABLE")
	private java.lang.String area_responsable;

	public DATOS_PQRS() {
	}

	public java.lang.String getCliente() {
		return this.cliente;
	}

	public void setCliente(java.lang.String cliente) {
		this.cliente = cliente;
	}

	public java.lang.String getTipo_novedad() {
		return this.tipo_novedad;
	}

	public void setTipo_novedad(java.lang.String tipo_novedad) {
		this.tipo_novedad = tipo_novedad;
	}

	public java.lang.String getDescripcion_novedad() {
		return this.descripcion_novedad;
	}

	public void setDescripcion_novedad(java.lang.String descripcion_novedad) {
		this.descripcion_novedad = descripcion_novedad;
	}

	public java.lang.String getOtra_solicitud() {
		return this.otra_solicitud;
	}

	public void setOtra_solicitud(java.lang.String otra_solicitud) {
		this.otra_solicitud = otra_solicitud;
	}

	public java.lang.String getArea_responsable() {
		return this.area_responsable;
	}

	public void setArea_responsable(java.lang.String area_responsable) {
		this.area_responsable = area_responsable;
	}

	public DATOS_PQRS(java.lang.String cliente, java.lang.String tipo_novedad,
			java.lang.String descripcion_novedad,
			java.lang.String otra_solicitud, java.lang.String area_responsable) {
		this.cliente = cliente;
		this.tipo_novedad = tipo_novedad;
		this.descripcion_novedad = descripcion_novedad;
		this.otra_solicitud = otra_solicitud;
		this.area_responsable = area_responsable;
	}

}